package com.legacylifter.common.entity;

import jakarta.persistence.*;

/**
 * A single modernization suggestion generated by the AI engine.
 * Contains original code, modernized code, explanation, and risk assessment.
 */
@Entity
@Table(name = "modernization_suggestions")
public class ModernizationSuggestion extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modernization_run_id", nullable = false)
    private ModernizationRun modernizationRun;

    @Column(name = "strategy_type", nullable = false)
    private String strategyType;

    @Column(name = "file_path", nullable = false)
    private String filePath;

    @Column(name = "original_code", columnDefinition = "TEXT")
    private String originalCode;

    @Column(name = "modernized_code", columnDefinition = "TEXT")
    private String modernizedCode;

    @Column(name = "explanation", columnDefinition = "TEXT")
    private String explanation;

    @Column(name = "confidence_score")
    private float confidenceScore;

    @Enumerated(EnumType.STRING)
    @Column(name = "risk_level")
    private RiskLevel riskLevel = RiskLevel.MEDIUM;

    @Column(name = "applied")
    private boolean applied = false;

    public enum RiskLevel {
        LOW, MEDIUM, HIGH
    }

    // ============================================================
    // Getters & Setters
    // ============================================================

    public ModernizationRun getModernizationRun() { return modernizationRun; }
    public void setModernizationRun(ModernizationRun modernizationRun) { this.modernizationRun = modernizationRun; }

    public String getStrategyType() { return strategyType; }
    public void setStrategyType(String strategyType) { this.strategyType = strategyType; }

    public String getFilePath() { return filePath; }
    public void setFilePath(String filePath) { this.filePath = filePath; }

    public String getOriginalCode() { return originalCode; }
    public void setOriginalCode(String originalCode) { this.originalCode = originalCode; }

    public String getModernizedCode() { return modernizedCode; }
    public void setModernizedCode(String modernizedCode) { this.modernizedCode = modernizedCode; }

    public String getExplanation() { return explanation; }
    public void setExplanation(String explanation) { this.explanation = explanation; }

    public float getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(float confidenceScore) { this.confidenceScore = confidenceScore; }

    public RiskLevel getRiskLevel() { return riskLevel; }
    public void setRiskLevel(RiskLevel riskLevel) { this.riskLevel = riskLevel; }

    public boolean isApplied() { return applied; }
    public void setApplied(boolean applied) { this.applied = applied; }
}
